### ISSUE TITLE
Allow html code filtering... 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wangvisual/expression-search#21]
```
The tb's internal body filtering system allows filtering the html code,
for body (regex), please allow me to filter in the html code (tags included)
section, for a more precise filtration.

Thank you
```

Original issue reported on code.google.com by `ukrainia...@gmail.com` on 29 May 2014 at 10:48

**Comment by r2evans** [comment]
@wangvisual  I see this thread (albeit closed) so I won't create a new issue yet. This topic is interesting to me: allowing the search to match tags within the HTML portion of the email. Because of the "`deleted comment`" portions in the above conversation, I think I'm missing a lot, but it seems that the suggested fixes did not address the original question.

If the problem is because TB's underlying search will not allow it, then the problem is perhaps unsolvable (through that search mechanism). If it is something else, however, is there a way to optionally match HTML tags?

(using version 1.2 on TB 52.5.2 on win10)
